CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(50) NOT NULL,
  "age" int NOT NULL,
  "roles" int NOT NULL
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100) NOT NULL,
  "level" varchar(20) UNIQUE NOT NULL,
  "teacher" varchar(30) NOT NULL,
  "categorie" int NOT NULL
);

CREATE TABLE "Courses_Video" (
  "course" int NOT NULL,
  "title" varchar(20) NOT NULL,
  "url" varchar(100) NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "Courses_User" (
  "user" int NOT NULL,
  "courser" int NOT NULL
);

ALTER TABLE "Courses_Video" ADD FOREIGN KEY ("course") REFERENCES "Courses" ("id");

ALTER TABLE "User" ADD FOREIGN KEY ("roles") REFERENCES "Roles" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("categorie") REFERENCES "Categories" ("id");

ALTER TABLE "Courses_User" ADD FOREIGN KEY ("courser") REFERENCES "Courses" ("id");

ALTER TABLE "Courses_User" ADD FOREIGN KEY ("user") REFERENCES "User" ("id");

INSERT INTO User ("kevin","kevin@gmail.com","123456",27,),("Mayra","mayra@gmail.com","78945",30);
INSERT INTO Courses ("pintura","curso de pintura para principiantes","1","Ruth"), ("programacion","programacion avanzada","3","Jose");
INSERT INTO Courses_Video ("Gama de colores","https:chalala.com"),("Eficiencia de algoritmos","https:chalala.com");
INSERT INTO Categories ("Artes"),("Programacion");
INSERT INTO Roles ("Estudiante"),("Profesor");


